### ISSUE TITLE
Modifica file "Guida per lo studente.md" per personalizzazione delle figure

### ISSUE THREAD

**Issue by matera02** [softeng2223-inf-uniba/progetto2223-codd#5]
Modifica del file markdown _Guida per lo studente.md_, personalizzando le figure in cui compare un nome di repository diverso dal proprio, oppure uno username o immagine di profilo diverso da quello dei componenti del gruppo.

**Comment by giosteh** [comment]
Ho riaperto l'issue a seguito al revert di #11.
